#! /usr/bin/env python
"""Arcane 

This encryption tool connects to a specified IMAP4 compatible mail
server, authenticates with a given username/password and encrypts all
unencrypted mail in the users mailbox.

The MIT License (MIT)

Copyright (c) 2013 Matthias Fassl <mf@n0g.at>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

"""
import sys
import argparse
import getpass
import imap
from util import Util
from gpg import GPGDecryption
from gpg import GPGEncryption

DEFAULT_SSL_PORT = 993
DEFAULT_PORT = 143

def main(argv=None):
	parser = argparse.ArgumentParser(description="Connect to your mailbox (via imap) and encrypt all your mails with PGP")
	parser.add_argument('-a','--address',help="Address of IMAP4 compatible mailserver",required=True)
	parser.add_argument('-p','--port',help="Optional port number of IMAP4 service",type=int)
	parser.add_argument('-s','--ssl',help="Optional SSL flag (changes default port to 993)",action='store_true')
	parser.add_argument('-m','--mailbox',help="Optional Mailbox that specifies which Mailbox should be encrypted")
	parser.add_argument('-u','--username',help="Username that should be used for authentication",required=True)
	parser.add_argument('-d','--decrypt',help="Optional argument for decryption (useful for key rollover)",action='store_true')
	parser.add_argument('-k','--key',help="Public key Identifier that will be used to encrypt the mails",required=True,nargs='+')
	ns = parser.parse_args()
	
	# choose correct port
	if not ns.port:
		if ns.ssl:
			ns.port = DEFAULT_SSL_PORT
		else:
			ns.port = DEFAULT_PORT

	# check number of key arguments
	if ns.decrypt and len(key) > 1:
		print sys.stderr, "Warning: Only the first given PGP key will be used for decryption"

	# fetch passwords from user
	imap_password = getpass.getpass("IMAP4 Password: ")
	if ns.decrypt:
		gpg_passphrase = getpass.getpass("GPG Passphrase: ")

	# open connection
	conn = imap.IMAPConnection(ns.address,ns.port,ns.ssl,ns.username,imap_password)

	# iterate over all mails and encrypt or decrypt them
	for mbox in conn:
		if ns.mailbox and not ns.mailbox in mbox.mailbox:
			continue
		print mbox
		for mail in mbox:
			if not ns.decrypt:
				if not mail.isEncrypted():
					mail.mail = GPGEncryption().encryptPGP(mail.mail,ns.key)
					mail.store()
					sys.stdout.write('.')
				else:
					sys.stdout.write('X')
			else:
				if mail.isEncrypted():
					mail.mail = GPGDecryption().decryptPGP(mail.mail,ns.key[0],gpg_passphrase)
					mail.store()
					sys.stdout.write('.')
				else:
					sys.stdout.write('X')
			sys.stdout.flush()
		print "\n"

if __name__  == "__main__":
	sys.exit(main())
