#! /usr/bin/env python
""" arcane-is-encrypted

Reads an E-Mail from Standard Input and checks if it is encrypted or
not.

The MIT License (MIT)

Copyright (c) 2013 Matthias Fassl <mf@n0g.at>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

import sys
import email

def main(argv=None):
	if argv==None:
		argv = sys.argv

	# check options
	if len(argv) > 1:
		usage()

	# read email from stdin
	email_lines = sys.stdin.readlines()
	email_data = ''.join(email_lines)
	email_obj = email.message_from_string(email_data)

	# check if it is encrypted
	if email_obj.get_content_type() == "multipart/encrypted":
		return 0
	else:
		return 1


def usage():
	print >> sys.stderr, "Usage: arcane-is-encrypted"
	
if __name__  == "__main__":
	sys.exit(main())
