#! /usr/bin/env python
"""Arcane 

This encryption tool connects to a specified IMAP4 compatible mail
server, authenticates with a given username/password and encrypts all
unencrypted mail in the users mailbox.

The MIT License (MIT)

Copyright (c) 2013 Matthias Fassl <mf@n0g.at>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

"""

import re
import os
import sys
import getopt
import getpass
import email

from util import Util
from gpg import GPGDecryption
from gpg import GPGEncryption

def is_encrypted(mail):
	return mail.get_content_type() == "multipart/encrypted"

def main(argv=None):
	if argv==None:
		argv = sys.argv

	# Initial Arguments
	key = ""
	decrypt = False

	# parse arguments
	try:
		optlist, args = getopt.getopt(sys.argv[1:],"h:p:su:k:m:d",["key=","mailbox=","decrypt"])
	except getopt.GetoptError as err:
		usage()
		return 2


	for o, a in optlist:
		if o in ("-k","--key"):
			key = a
		elif o in ("-m","--mailbox"):
			mbox = a
		elif o in ("-d","--decrypt"):
			decrypt = True
		else:
			usage()
			return 1

	if key == "":
		print >> sys.stderr,"Encryption not possible without key identifier\n"
		usage()
		return 1
		
	# fetch passwords from user
	if decrypt == True:
		gpg_passphrase = getpass.getpass("GPG Passphrase: ")

	re_mbox = re.compile('[0-9\.]+\.mbox.*')

	# iterate over all mails and encrypt or decrypt them
	for root, subFolders, files in os.walk(mbox):
		files = filter(re_mbox.match, files)
		for mailbox in files:
			with open(os.path.join(root, mailbox), 'r') as f:
				mail = email.message_from_file(f)
				
			if decrypt == False:
				if not is_encrypted(mail):
					mail = GPGEncryption().encryptPGP(mail, key)
					with open(os.path.join(root, mailbox), 'w') as f:
						f.write(mail.as_string())
					
					sys.stdout.write('.')
				else:
					sys.stdout.write('X')
			else:
				if is_encrypted(mail):
					mail = GPGDecryption().decryptPGP(mail, key, gpg_passphrase)
					with open(os.path.join(root, mailbox), 'w') as f:
						f.write(mail.as_string())
					sys.stdout.write('.')
				else:
					sys.stdout.write('X')
			sys.stdout.flush()
		print "\n"

def usage():
	print >> sys.stderr, "Usage: arcane [-m mailbox] [-d] -k identifier"
	print >> sys.stderr, "\t-k,--key\tPublic key Identifier that will be used to encrypt the mails"
	print >> sys.stderr, "\t-m,--mailbox\tOptional Mailbox that specifies which Mailbox should be encrypted"
	print >> sys.stderr, "\t-d,--decrypt\tOptional argument for decryption (useful for key rollover)"
	

if __name__  == "__main__":
	sys.exit(main())
