#! /usr/bin/env python
"""Arcane 

This encryption tool connects to a specified IMAP4 compatible mail
server, authenticates with a given username/password and encrypts all
unencrypted mail in the users mailbox.

The Encryption should be possible with X.509 Certificates and Public PGP
Keys (using a gpg library). There is also an option to reencrypt already
encrypted E-Mails with a different public key (for a nice key-rollover
procedure).

Last but not least a daemon function, where incoming mail is encrypted
would also be nice.
"""
import sys
import getopt
import getpass
import imaplib

def main(argv=None):
	if argv==None:
		argv = sys.argv
	print "Hello, World!"

if __name__  == "__main__":
	sys.exit(main())



